// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// densify.cpp
list densify_path_cpp(doubles lon, doubles lat, std::string from, std::string to, double tol, int max_depth);
extern "C" SEXP _bigcurve_densify_path_cpp(SEXP lon, SEXP lat, SEXP from, SEXP to, SEXP tol, SEXP max_depth) {
  BEGIN_CPP11
    return cpp11::as_sexp(densify_path_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<std::string>>(from), cpp11::as_cpp<cpp11::decay_t<std::string>>(to), cpp11::as_cpp<cpp11::decay_t<double>>(tol), cpp11::as_cpp<cpp11::decay_t<int>>(max_depth)));
  END_CPP11
}
// densify.cpp
list densify_mesh_cpp(doubles x, doubles y, integers s0, integers s1, std::string from, std::string to, double tol, int max_depth);
extern "C" SEXP _bigcurve_densify_mesh_cpp(SEXP x, SEXP y, SEXP s0, SEXP s1, SEXP from, SEXP to, SEXP tol, SEXP max_depth) {
  BEGIN_CPP11
    return cpp11::as_sexp(densify_mesh_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<doubles>>(y), cpp11::as_cpp<cpp11::decay_t<integers>>(s0), cpp11::as_cpp<cpp11::decay_t<integers>>(s1), cpp11::as_cpp<cpp11::decay_t<std::string>>(from), cpp11::as_cpp<cpp11::decay_t<std::string>>(to), cpp11::as_cpp<cpp11::decay_t<double>>(tol), cpp11::as_cpp<cpp11::decay_t<int>>(max_depth)));
  END_CPP11
}
// proj.cpp
list proj_coords(list xy, std::string from, std::string to);
extern "C" SEXP _bigcurve_proj_coords(SEXP xy, SEXP from, SEXP to) {
  BEGIN_CPP11
    return cpp11::as_sexp(proj_coords(cpp11::as_cpp<cpp11::decay_t<list>>(xy), cpp11::as_cpp<cpp11::decay_t<std::string>>(from), cpp11::as_cpp<cpp11::decay_t<std::string>>(to)));
  END_CPP11
}
// proj.cpp
std::string proj_version_cpp();
extern "C" SEXP _bigcurve_proj_version_cpp() {
  BEGIN_CPP11
    return cpp11::as_sexp(proj_version_cpp());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_bigcurve_densify_mesh_cpp", (DL_FUNC) &_bigcurve_densify_mesh_cpp, 8},
    {"_bigcurve_densify_path_cpp", (DL_FUNC) &_bigcurve_densify_path_cpp, 6},
    {"_bigcurve_proj_coords",      (DL_FUNC) &_bigcurve_proj_coords,      3},
    {"_bigcurve_proj_version_cpp", (DL_FUNC) &_bigcurve_proj_version_cpp, 0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_bigcurve(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
