# Generated by cpp11: do not edit by hand

densify_path_cpp <- function(lon, lat, from, to, tol, max_depth) {
  .Call(`_bigcurve_densify_path_cpp`, lon, lat, from, to, tol, max_depth)
}

densify_mesh_cpp <- function(x, y, s0, s1, from, to, tol, max_depth) {
  .Call(`_bigcurve_densify_mesh_cpp`, x, y, s0, s1, from, to, tol, max_depth)
}

proj_coords <- function(xy, from, to) {
  .Call(`_bigcurve_proj_coords`, xy, from, to)
}

proj_version_cpp <- function() {
  .Call(`_bigcurve_proj_version_cpp`)
}
