# Generated by cpp11: do not edit by hand

cpp_libproj_init_api <- function() {
  invisible(.Call(`_bigcurve_cpp_libproj_init_api`))
}

proj_coords <- function(xy, from, to) {
  .Call(`_bigcurve_proj_coords`, xy, from, to)
}

mid_pt1 <- function(x1, x2) {
  .Call(`_bigcurve_mid_pt1`, x1, x2)
}

gc_dist1 <- function(lon1, lat1, lon2, lat2) {
  .Call(`_bigcurve_gc_dist1`, lon1, lat1, lon2, lat2)
}

bisect1 <- function(xy, from, to) {
  .Call(`_bigcurve_bisect1`, xy, from, to)
}
